### ISSUE TITLE
Mysql Connector update

### ISSUE THREAD

**Issue by NeverGrowUp** [AddstarMC/craftconomy3#34]
Paper Commit https://github.com/PaperMC/Paper/pull/5474/commits/bc91b5d07b3d049582320b400b767f4fea70e73c updated MySql version from 5.1.49 to 8.0.23. Upon server restart with this commit applied (Using Tuinity build 224) the below stack occurs. Going back to Tuinity build 217, CraftConomy loads fine.
Thinking this line: https://github.com/AddstarMC/craftconomy3/blob/923a2f8eb1fa03ad597e5b3570c5913274464d10/src/main/java/com/greatmancode/craftconomy3/storage/sql/MySQLEngine.java#L40 needs to be changed to: 
> hikari.setDataSourceClassName("com.mysql.cj.jdbc.MysqlDataSource");

Stacktrace:
```
2021-04-17 21:36:51 [Server thread/INFO]: Enabling Craftconomy3 v3.4.0-SNAPSHOT-31
2021-04-17 21:36:51 [Server thread/INFO]: Starting up!
2021-04-17 21:36:51 [Server thread/INFO]: Loading the Configuration
2021-04-17 21:36:51 [Server thread/INFO]: Loading listeners.
2021-04-17 21:36:51 [Server thread/INFO]: Loading commands
2021-04-17 21:36:52 [Server thread/INFO]: Loading the Database Manager
2021-04-17 21:36:52 [Server thread/WARN]: SLF4J: No SLF4J providers were found.
2021-04-17 21:36:52 [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
2021-04-17 21:36:52 [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
2021-04-17 21:36:52 [Server thread/ERROR]: Error occurred while enabling Craftconomy3 v3.4.0-SNAPSHOT-31 (Is it up to date?)
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        at com.greatmancode.com.zaxxer.libs.hikari.util.UtilityElf.createInstance(UtilityElf.java:113) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:332) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.pool.PoolBase.<init>(PoolBase.java:109) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at com.greatmancode.craftconomy3.storage.sql.MySQLEngine.<init>(MySQLEngine.java:64) ~[?:?]
        at com.greatmancode.craftconomy3.storage.StorageHandler.<init>(StorageHandler.java:40) ~[?:?]
        at com.greatmancode.craftconomy3.Common.initialiseDatabase(Common.java:389) ~[?:?]
        at com.greatmancode.craftconomy3.Common.onEnable(Common.java:138) ~[?:?]
        at com.greatmancode.craftconomy3.tools.interfaces.BukkitLoader.onEnable(BukkitLoader.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:581) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1057) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Tuinity-"7d36676"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.util.UtilityElf.createInstance(UtilityElf.java:100) ~[?:?]
        ... 19 more
2021-04-17 21:36:52 [Server thread/INFO]: Disabling Craftconomy3 v3.4.0-SNAPSHOT-31
```

**Comment by addstar** [comment]
A quick google looks like you might be spot on :+1: I think we can just change the line to use that new class.

@NeverGrowUp Did you want to try making the change yourself? Not sure if the Hikari version in maven needs to be bumped too, but it's worth looking in to (dependency version is in the [pom.xml](https://github.com/AddstarMC/craftconomy3/blob/master/pom.xml#L140))

**Comment by addstar** [comment]
HikariCP repo seems to indicate the recommend version to use now is:
```
    <dependency>
        <groupId>com.zaxxer</groupId>
        <artifactId>HikariCP</artifactId>
        <version>4.0.3</version>
    </dependency>
```

https://github.com/brettwooldridge/HikariCP
